airlineCodes = {
  AA: "American Airlines",
  AC: "Air Canada",
  AF: "Air France",
  AI: "Air India",
  AM: "Aeromexico",
  AS: "Alaska Airlines",
  AY: "Finnair",
  AZ: "Alitalia",
  BA: "British Airways",
  BI: "Royal Brunei Airlines",
  BR: "EVA Air",
  CA: "Air China",
  CI: "China Airlines",
  CX: "Cathay Pacific",
  CZ: "China Southern Airlines",
  DL: "Delta Air Lines",
  EK: "Emirates",
  ET: "Ethiopian Airlines",
  EY: "Etihad Airways",
  FJ: "Fiji Airways",
  GA: "Garuda Indonesia",
  HA: "Hawaiian Airlines",
  HU: "Hainan Airlines Holding Company Limited",
  IB: "Iberia",
  JL: "Japan Airlines",
  KE: "Korean Air",
  KL: "KLM Royal Dutch Airlines",
  LA: "LATAM Airlines",
  LH: "Lufthansa",
  LO: "LOT Polish Airlines",
  LX: "Swiss International Air Lines",
  LY: "El Al Israel Airlines",
  MH: "Malaysia Airlines",
  MK: "Air Mauritius",
  MS: "EgyptAir",
  MU: "China Eastern Airlines",
  NH: "All Nippon Airways",
  NZ: "Air New Zealand",
  OS: "Austrian Airlines",
  OU: "Croatia Airlines",
  OZ: "Asiana Airlines",
  PG: "Bangkok Airways",
  PR: "Philippine Airlines",
  QF: "Qantas",
  QR: "Qatar Airways",
  RJ: "Royal Jordanian",
  RO: "Tarom",
  SA: "South African Airways",
  SK: "Scandinavian Airlines",
  SQ: "Singapore Airlines",
  SU: "Aeroflot",
  SV: "Saudi Arabian Airlines",
  TG: "Thai Airways",
  TK: "Turkish Airlines",
  TN: "Air Tahiti Nui",
  TP: "TAP Air Portugal",
  UA: "United Airlines",
  UL: "SriLankan Airlines",
  UX: "Air Europa",
  VN: "Vietnam Airlines",
  VS: "Virgin Atlantic",
  WF: "Widerøe",
  WN: "Southwest Airlines",
  WS: "WestJet",
  XY: "Flynas",
  XJ: "Thai AirAsia X",
  ZB: "Monarch Airlines",
  ZI: "Aigle Azur",
  ZL: "Regional Express Airlines",
  "5J": "Cebu Pacific",
  "6E": "IndiGo",
  "7C": "Jeju Air",
  "8L": "Lucky Air",
  "9W": "Jet Airways",
  A3: "Aegean Airlines",
  B6: "JetBlue Airways",
  D8: "Norwegian Air Shuttle",
  DY: "Norwegian Air International",
  EI: "Aer Lingus",
  G3: "Gol Transportes Aéreos",
  HU: "Hainan Airlines",
  HY: "Uzbekistan Airways",
  JD: "Beijing Capital Airlines",
  JJ: "LATAM Airlines Brasil",
  JQ: "Jetstar Airways",
  JT: "Lion Air",
  KA: "Cathay Dragon",
  MF: "XiamenAir",
  MK: "Air Mauritius",
  MM: "Peach Aviation",
  MS: "EgyptAir",
  OK: "Czech Airlines",
  QR: "Qatar Airways",
  S7: "S7 Airlines",
  SN: "Brussels Airlines",
  U2: "easyJet",
  UL: "SriLankan Airlines",
  VA: "Virgin Australia",
  VY: "Vueling",
  X3: "TUIfly",
  ZB: "Monarch Airlines",
  AB: "Air Berlin",
  BT: "Air Baltic",
  BV: "Blue Panorama Airlines",
  BY: "Thomson Airways",
  CE: "Chalair Aviation",
  CY: "Cyprus Airways",
  D9: "Donavia",
  DE: "Condor",
  E9: "Evelop Airlines",
  EW: "Eurowings",
  EZ: "Sun Air of Scandinavia",
  FB: "Bulgaria Air",
  FC: "Finncomm Airlines",
  FV: "Rossiya Airlines",
  GM: "Germania",
  GQ: "Sky Express",
  HV: "Transavia",
  IB: "Iberia",
  IG: "Meridiana",
  IZ: "Arkia",
  J2: "Azerbaijan Airlines",
  JU: "Air Serbia",
  KM: "Air Malta",
  KP: "ASKY Airlines",
  LG: "Luxair",
  LZ: "Balkan Bulgarian Airlines",
  M4: "Poste Air Cargo",
  MB: "MNG Airlines",
  MZ: "Merpati Nusantara Airlines",
  N4: "Nordwind Airlines",
  NP: "Nile Air",
  OE: "Lauda",
  OK: "Czech Airlines",
  OV: "Estonian Air",
  PC: "Pegasus Airlines",
  PS: "Ukraine International Airlines",
  QS: "SmartWings",
  RK: "Ryanair UK",
  RO: "Tarom",
  S4: "Azores Airlines",
  SP: "SATA Air Acores",
  SS: "Corsair International",
  SX: "SkyWork Airlines",
  TF: "Braathens Regional Airlines",
  TO: "Transavia France",
  TU: "Tunisair",
  TX: "Air Caraïbes",
  U6: "Ural Airlines",
  UX: "Air Europa",
  V7: "Volotea",
  VG: "VLM Airlines",
  VR: "TACV",
  VZ: "Thai Vietjet Air",
  W2: "FlexFlight",
  WB: "RwandAir",
  WI: "White Airways",
  WK: "Edelweiss Air",
  WU: "Wizz Air Ukraine",
  WW: "WOW air",
  WX: "CityJet",
  YW: "Air Nostrum",
  ZB: "Monarch Airlines",
  A5: "HOP!",
  A9: "Georgian Airways",
  AQ: "9 Air",
  B2: "Belavia",
  C3: "Trade Air",
  C8: "Cronos Airlines",
  CE: "Chalair Aviation",
  D2: "Severstal Aircompany",
  E5: "Air Arabia Egypt",
  ED: "Air Explore",
  F7: "Flybaboo",
  FX: "Federal Express",
  GQ: "Sky Express",
  H4: "HiSky",
  I2: "Iberia Express",
  I9: "Air Italy",
  J7: "Afrijet Business Service",
  K4: "Kalitta Air",
  KU: "Kuwait Airways",
  LM: "Loganair",
  LT: "LongJiang Airlines",
  ML: "Air Méditerranée",
  MR: "Hunnu Air",
  NH: "All Nippon Airways",
  NT: "Binter Canarias",
  OF: "Enter Air",
  PE: "People's Viennaline",
  PG: "Bangkok Airways",
  PQ: "SkyUp Airlines",
  Q6: "VivaColombia",
  RA: "Nepal Airlines",
  R3: "Yakutia Airlines",
  RD: "Ryan International Airlines",
  RF: "Florida West International Airways",
  S2: "Air Sahara",
  SC: "Shandong Airlines",
  SN: "Brussels Airlines",
  ST: "Germania",
  SY: "Sun Country Airlines",
  T3: "Eastern Airways",
  T7: "Twin Jet",
  TB: "TUI fly Belgium",
  TP: "TAP Portugal",
  TS: "Air Transat",
  U5: "USA3000 Airlines",
  UX: "Air Europa",
  VY: "Vueling",
  X5: "Fly African Cargo",
  XQ: "SunExpress",
  XW: "NokScoot",
  YK: "Avia Traffic Company",
  YM: "Montenegro Airlines",
  ZB: "Monarch Airlines",
  ZF: "Azur Air",
  ZX: "Air Georgian",
  AB: "Air Berlin",
  AD: "Azul Brazilian Airlines",
  AE: "Mandarin Airlines",
  AK: "AirAsia",
  AO: "Australian Airlines",
  AT: "Royal Air Maroc",
  AW: "CHC Airways",
  AX: "Trans States Airlines",
  AZ: "Alitalia",
  BB: "Seaborne Airlines",
  BC: "Skymark Airlines",
  BG: "Biman Bangladesh Airlines",
  BJ: "Nouvelair",
  BO: "Bouraq Indonesia Airlines",
  BP: "Air Botswana",
  BU: "Compagnie Africaine d'Aviation",
  C8: "Cargolux Italia",
  CA: "Air China",
  CB: "Suckling Airways",
  CC: "Macair Airlines",
  CD: "Corendon Dutch Airlines",
  CF: "China Postal Airlines",
  CH: "Bemidji Airlines",
  CI: "China Airlines",
  CN: "Grand China Air",
  CO: "Continental Airlines",
  CP: "Canadian Pacific Airlines",
  CQ: "Coastal Aviation",
  CS: "Continental Micronesia",
  CV: "Cargolux",
  CY: "Cyprus Airways",
  CZ: "China Southern Airlines",
  D3: "Daallo Airlines",
  D5: "DHL Aero Expreso",
  DL: "Delta Air Lines",
  DR: "Ruili Airlines",
  DZ: "Donghai Airlines",
  EA: "Eastern Air Lines",
  EB: "Air Pullmantur",
  EC: "OpenSkies",
  ED: "Airblue",
  EE: "Regional Jet",
  EG: "Japan Asia Airways",
  EH: "ANA Wings",
  EI: "Aer Lingus",
  EJ: "New England Airlines",
  EK: "Emirates",
  EL: "Ellinair",
  EM: "Empire Airlines",
  EN: "Air Dolomiti",
  EO: "flyCongo",
  EP: "Iran Aseman Airlines",
  EQ: "TAME",
  ER: "Astar Air Cargo",
  ES: "DHL International Aviation ME",
  ET: "Ethiopian Airlines",
  EV: "ExpressJet",
  EW: "Eurowings",
  EX: "Air Santo Domingo",
  EY: "Etihad Airways",
  EZ: "Sun Air of Scandinavia",
  F3: "Flyadeal",
  F9: "Frontier Airlines",
  FA: "Safair",
  FC: "Finncomm Airlines",
  FE: "Primaris Airlines",
  FF: "Airshop",
  FG: "Ariana Afghan Airlines",
  FI: "Icelandair",
  FJ: "Fiji Airways",
  FL: "AirTran Airways",
  FO: "Flybondi",
  FP: "Freedom Air",
  FQ: "Brindabella Airlines",
  FR: "Ryanair",
  FS: "Servicios de Transportes Aéreos Fueguinos",
  FT: "Siem Reap Airways",
  FV: "Rossiya Airlines",
  FW: "Ibex Airlines",
  FX: "FedEx Express",
  FY: "Firefly",
  G3: "Gol Linhas Aéreas",
  GA: "Garuda Indonesia",
  GC: "Gambia International Airlines",
  GE: "TransAsia Airways",
  GF: "Gulf Air",
  GG: "Cargo 360",
  GH: "Globus Airlines",
  GI: "Itek Air",
  GJ: "Eurofly",
  GK: "Jetstar Japan",
  GL: "Air Greenland",
  GM: "Germania Flug",
  GN: "Air Gabon",
  GO: "Ghana International Airlines",
  GQ: "Sky Express",
  GR: "Aurigny Air Services",
  GS: "Tianjin Airlines",
  GT: "GB Airways",
  GW: "Kuban Airlines",
};

function codeToAirline(code) {
  return airlineCodes[code] || "Ryanair";
}

export { codeToAirline };
