cityToEmojiLookup = {
  Atlanta: "🇺🇸",
  Beijing: "🇨🇳",
  Dubai: "🇦🇪",
  "Los Angeles": "🇺🇸",
  Tokyo: "🇯🇵",
  Chicago: "🇺🇸",
  London: "🇬🇧",
  "Hong Kong": "🇭🇰",
  Shanghai: "🇨🇳",
  Paris: "🇫🇷",
  Amsterdam: "🇳🇱",
  Guangzhou: "🇨🇳",
  Frankfurt: "🇩🇪",
  Istanbul: "🇹🇷",
  Singapore: "🇸🇬",
  Seoul: "🇰🇷",
  Denver: "🇺🇸",
  Bangkok: "🇹🇭",
  "New York (JFK)": "🇺🇸",
  "Kuala Lumpur": "🇲🇾",
  Madrid: "🇪🇸",
  "San Francisco": "🇺🇸",
  Chengdu: "🇨🇳",
  Shenzhen: "🇨🇳",
  "Las Vegas": "🇺🇸",
  Jakarta: "🇮🇩",
  Barcelona: "🇪🇸",
  "Mexico City": "🇲🇽",
  Toronto: "🇨🇦",
  Mumbai: "🇮🇳",
  Orlando: "🇺🇸",
  Munich: "🇩🇪",
  Sydney: "🇦🇺",
  "São Paulo": "🇧🇷",
  Rome: "🇮🇹",
  Moscow: "🇷🇺",
  Boston: "🇺🇸",
  "London (Gatwick)": "🇬🇧",
  Seattle: "🇺🇸",
  "Washington D.C. (Dulles)": "🇺🇸",
  Miami: "🇺🇸",
  Manchester: "🇬🇧",
  Delhi: "🇮🇳",
  Houston: "🇺🇸",
  Melbourne: "🇦🇺",
  Vienna: "🇦🇹",
  Oslo: "🇳🇴",
  Zurich: "🇨🇭",
  Copenhagen: "🇩🇰",
  Helsinki: "🇫🇮",
  Dublin: "🇮🇪",
  Brussels: "🇧🇪",
  Stockholm: "🇸🇪",
  Lisbon: "🇵🇹",
  Warsaw: "🇵🇱",
  Budapest: "🇭🇺",
  Prague: "🇨🇿",
  Athens: "🇬🇷",
  Milan: "🇮🇹",
  Kuwait: "🇰🇼",
  Doha: "🇶🇦",
  Osaka: "🇯🇵",
  "Tokyo (Narita)": "🇯🇵",
  Fukuoka: "🇯🇵",
  Sapporo: "🇯🇵",
  Auckland: "🇳🇿",
  Bogota: "🇨🇴",
  "Buenos Aires": "🇦🇷",
  Lima: "🇵🇪",
  Santiago: "🇨🇱",
  "Rio de Janeiro": "🇧🇷",
  "Cape Town": "🇿🇦",
  Johannesburg: "🇿🇦",
  Nairobi: "🇰🇪",
  Cairo: "🇪🇬",
  Casablanca: "🇲🇦",
  "Abu Dhabi": "🇦🇪",
  Bahrain: "🇧🇭",
  Riyadh: "🇸🇦",
  Jeddah: "🇸🇦",
  Muscat: "🇴🇲",
  Amman: "🇯🇴",
  Beirut: "🇱🇧",
  Tehran: "🇮🇷",
  Karachi: "🇵🇰",
  Lahore: "🇵🇰",
  Colombo: "🇱🇰",
  Dhaka: "🇧🇩",
  Kathmandu: "🇳🇵",
  Hanoi: "🇻🇳",
  "Ho Chi Minh City": "🇻🇳",
  Manila: "🇵🇭",
  "Phnom Penh": "🇰🇭",
  Yangon: "🇲🇲",
  Vientiane: "🇱🇦",
  "Luang Prabang": "🇱🇦",
  "Siem Reap": "🇰🇭",
  Danang: "🇻🇳",
  Phuket: "🇹🇭",
  "Chiang Mai": "🇹🇭",
  Penang: "🇲🇾",
  Birmingham: "🇬🇧",
  Glasgow: "🇬🇧",
  Edinburgh: "🇬🇧",
  Bristol: "🇬🇧",
  Newcastle: "🇬🇧",
  Liverpool: "🇬🇧",
  "London Stansted": "🇬🇧",
  "London Luton": "🇬🇧",
  Aberdeen: "🇬🇧",
  "Belfast International": "🇬🇧",
  "East Midlands": "🇬🇧",
  "Leeds Bradford": "🇬🇧",
  "Belfast City": "🇬🇧",
  Southampton: "🇬🇧",
  "London City": "🇬🇧",
  Cardiff: "🇬🇧",
  Inverness: "🇬🇧",
  Berlin: "🇩🇪",
  Geneva: "🇨🇭",
  Bucharest: "🇷🇴",
  Kuwait: "🇰🇼",
  Osaka: "🇯🇵",
  Fukuoka: "🇯🇵",
  Sapporo: "🇯🇵",
  "Buenos Aires": "🇦🇷",
  Lima: "🇵🇪",
  Santiago: "🇨🇱",
  "Rio de Janeiro": "🇧🇷",
  "Cape Town": "🇿🇦",
  Nairobi: "🇰🇪",
  Casablanca: "🇲🇦",
  Cairo: "🇪🇬",
  Bahrain: "🇧🇭",
  "Abu Dhabi": "🇦🇪",
  Jeddah: "🇸🇦",
  Amman: "🇯🇴",
  Beirut: "🇱🇧",
  Tehran: "🇮🇷",
  Lahore: "🇵🇰",
  Colombo: "🇱🇰",
  Dhaka: "🇧🇩",
  Kathmandu: "🇳🇵",
  Manila: "🇵🇭",
  Vientiane: "🇱🇦",
  "Luang Prabang": "🇱🇦",
  "Siem Reap": "🇰🇭",
  Yangon: "🇲🇲",
  "Ho Chi Minh City": "🇻🇳",
  Hanoi: "🇻🇳",
  Danang: "🇻🇳",
  "Kuala Lumpur": "🇲🇾",
  Penang: "🇲🇾",
  Singapore: "🇸🇬",
  Sydney: "🇦🇺",
  Melbourne: "🇦🇺",
  Brisbane: "🇦🇺",
  Perth: "🇦🇺",
  Adelaide: "🇦🇺",
  Wellington: "🇳🇿",
  Montreal: "🇨🇦",
  Calgary: "🇨🇦",
  Ottawa: "🇨🇦",
};

function cityToEmoji(city) {
  return cityToEmojiLookup[city] || null;
}

export { cityToEmoji };
