cityToCodeLookup = {
  Atlanta: "ATL",
  Beijing: "PEK",
  Dubai: "DXB",
  "Los Angeles": "LAX",
  Tokyo: "HND",
  Chicago: "ORD",
  London: "LHR",
  "Hong Kong": "HKG",
  Shanghai: "PVG",
  Paris: "CDG",
  Amsterdam: "AMS",
  Guangzhou: "CAN",
  Frankfurt: "FRA",
  Istanbul: "IST",
  Singapore: "SIN",
  Seoul: "ICN",
  Denver: "DEN",
  Bangkok: "BKK",
  "New York (JFK)": "JFK",
  "Kuala Lumpur": "KUL",
  Madrid: "MAD",
  "San Francisco": "SFO",
  Chengdu: "CTU",
  Shenzhen: "SZX",
  "Las Vegas": "LAS",
  Jakarta: "CGK",
  Barcelona: "BCN",
  "Mexico City": "MEX",
  Toronto: "YYZ",
  Mumbai: "BOM",
  Orlando: "MCO",
  Munich: "MUC",
  Sydney: "SYD",
  "São Paulo": "GRU",
  Rome: "FCO",
  Moscow: "SVO",
  Boston: "BOS",
  "London (Gatwick)": "LGW",
  Seattle: "SEA",
  "Washington D.C. (Dulles)": "IAD",
  Miami: "MIA",
  Manchester: "MAN",
  Delhi: "DEL",
  Houston: "IAH",
  Melbourne: "MEL",
  Vienna: "VIE",
  Oslo: "OSL",
  Zurich: "ZRH",
  Copenhagen: "CPH",
  Helsinki: "HEL",
  Dublin: "DUB",
  Brussels: "BRU",
  Stockholm: "ARN",
  Lisbon: "LIS",
  Warsaw: "WAW",
  Budapest: "BUD",
  Prague: "PRG",
  Athens: "ATH",
  Milan: "MXP",
  Vienna: "VIE",
  Helsinki: "HEL",
  Brussels: "BRU",
  Kuwait: "KWI",
  Doha: "DOH",
  Osaka: "KIX",
  "Tokyo (Narita)": "NRT",
  Fukuoka: "FUK",
  Sapporo: "CTS",
  Auckland: "AKL",
  Bogota: "BOG",
  "Buenos Aires": "EZE",
  Lima: "LIM",
  Santiago: "SCL",
  "Rio de Janeiro": "GIG",
  "Cape Town": "CPT",
  Johannesburg: "JNB",
  Nairobi: "NBO",
  Cairo: "CAI",
  Casablanca: "CMN",
  "Abu Dhabi": "AUH",
  Bahrain: "BAH",
  Riyadh: "RUH",
  Jeddah: "JED",
  Muscat: "MCT",
  Amman: "AMM",
  Beirut: "BEY",
  Tehran: "IKA",
  Karachi: "KHI",
  Lahore: "LHE",
  Colombo: "CMB",
  Dhaka: "DAC",
  Kathmandu: "KTM",
  Hanoi: "HAN",
  "Ho Chi Minh City": "SGN",
  Manila: "MNL",
  Bangkok: "BKK",
  "Phnom Penh": "PNH",
  Yangon: "RGN",
  Hanoi: "HAN",
  Vientiane: "VTE",
  "Luang Prabang": "LPQ",
  "Siem Reap": "REP",
  Danang: "DAD",
  Phuket: "HKT",
  "Chiang Mai": "CNX",
  "Kuala Lumpur": "KUL",
  Penang: "PEN",
  Singapore: "SIN",
  "London Heathrow": "LHR",
  "London Gatwick": "LGW",
  Manchester: "MAN",
  Birmingham: "BHX",
  Glasgow: "GLA",
  Edinburgh: "EDI",
  Bristol: "BRS",
  Newcastle: "NCL",
  Liverpool: "LPL",
  "London Stansted": "STN",
  "London Luton": "LTN",
  Aberdeen: "ABZ",
  "Belfast International": "BFS",
  "East Midlands": "EMA",
  "Leeds Bradford": "LBA",
  "Belfast City": "BHD",
  Southampton: "SOU",
  "London City": "LCY",
  Cardiff: "CWL",
  Inverness: "INV",
  Amsterdam: "AMS",
  Athens: "ATH",
  Barcelona: "BCN",
  Berlin: "BER",
  Brussels: "BRU",
  Bucharest: "OTP",
  Budapest: "BUD",
  Copenhagen: "CPH",
  Dublin: "DUB",
  Edinburgh: "EDI",
  Frankfurt: "FRA",
  Geneva: "GVA",
  Helsinki: "HEL",
  Istanbul: "IST",
  Lisbon: "LIS",
  London: "LHR",
  Madrid: "MAD",
  Milan: "MXP",
  Moscow: "SVO",
  Munich: "MUC",
  Oslo: "OSL",
  Paris: "CDG",
  Prague: "PRG",
  Rome: "FCO",
  Stockholm: "ARN",
  Vienna: "VIE",
  Warsaw: "WAW",
  Zurich: "ZRH",
  "Abu Dhabi": "AUH",
  Bangkok: "BKK",
  Beijing: "PEK",
  Cairo: "CAI",
  Delhi: "DEL",
  Doha: "DOH",
  Dubai: "DXB",
  "Hong Kong": "HKG",
  Jakarta: "CGK",
  Johannesburg: "JNB",
  "Kuala Lumpur": "KUL",
  Manila: "MNL",
  Mumbai: "BOM",
  Nairobi: "NBO",
  Osaka: "KIX",
  Riyadh: "RUH",
  Seoul: "ICN",
  Shanghai: "PVG",
  Singapore: "SIN",
  Sydney: "SYD",
  Taipei: "TPE",
  Tokyo: "NRT",
  Toronto: "YYZ",
  Vancouver: "YVR",
  Chicago: "ORD",
  Washington: "IAD",
  Atlanta: "ATL",
  Miami: "MIA",
  Boston: "BOS",
  Dallas: "DFW",
  Denver: "DEN",
  Houston: "IAH",
  Seattle: "SEA",
  Philadelphia: "PHL",
  Phoenix: "PHX",
  Minneapolis: "MSP",
  Detroit: "DTW",
  Orlando: "MCO",
  Montreal: "YUL",
  Calgary: "YYC",
  Ottawa: "YOW",
  Auckland: "AKL",
  Brisbane: "BNE",
  Melbourne: "MEL",
  Perth: "PER",
  Adelaide: "ADL",
  Wellington: "WLG",
};
codeToCityLookup = {
  ATL: "Atlanta",
  PEK: "Beijing",
  DXB: "Dubai",
  LAX: "Los Angeles",
  HND: "Tokyo",
  ORD: "Chicago",
  LHR: "London",
  HKG: "Hong Kong",
  PVG: "Shanghai",
  CDG: "Paris",
  AMS: "Amsterdam",
  DFW: "Dallas/Fort Worth",
  CAN: "Guangzhou",
  FRA: "Frankfurt",
  IST: "Istanbul",
  SIN: "Singapore",
  ICN: "Seoul",
  DEN: "Denver",
  BKK: "Bangkok",
  JFK: "New York (JFK)",
  KUL: "Kuala Lumpur",
  MAD: "Madrid",
  SFO: "San Francisco",
  CTU: "Chengdu",
  SZX: "Shenzhen",
  LAS: "Las Vegas",
  CGK: "Jakarta",
  BCN: "Barcelona",
  MEX: "Mexico City",
  YYZ: "Toronto",
  BOM: "Mumbai",
  MCO: "Orlando",
  MUC: "Munich",
  SYD: "Sydney",
  GRU: "São Paulo",
  FCO: "Rome",
  SVO: "Moscow",
  BOS: "Boston",
  LGW: "London (Gatwick)",
  SEA: "Seattle",
  IAD: "Washington D.C. (Dulles)",
  MIA: "Miami",
  MAN: "Manchester",
  DEL: "Delhi",
  IAH: "Houston",
  MEL: "Melbourne",
  VIE: "Vienna",
  OSL: "Oslo",
  ZRH: "Zurich",
  CPH: "Copenhagen",
  HEL: "Helsinki",
  DUB: "Dublin",
  BRU: "Brussels",
  ARN: "Stockholm",
  LIS: "Lisbon",
  WAW: "Warsaw",
  BUD: "Budapest",
  PRG: "Prague",
  ATH: "Athens",
  MXP: "Milan",
  VIE: "Vienna",
  HEL: "Helsinki",
  BRU: "Brussels",
  KWI: "Kuwait",
  DOH: "Doha",
  KIX: "Osaka",
  NRT: "Tokyo (Narita)",
  FUK: "Fukuoka",
  CTS: "Sapporo",
  AKL: "Auckland",
  BOG: "Bogota",
  EZE: "Buenos Aires",
  LIM: "Lima",
  SCL: "Santiago",
  GIG: "Rio de Janeiro",
  CPT: "Cape Town",
  JNB: "Johannesburg",
  NBO: "Nairobi",
  CAI: "Cairo",
  CMN: "Casablanca",
  AUH: "Abu Dhabi",
  BAH: "Bahrain",
  RUH: "Riyadh",
  JED: "Jeddah",
  MCT: "Muscat",
  AMM: "Amman",
  BEY: "Beirut",
  IKA: "Tehran",
  KHI: "Karachi",
  LHE: "Lahore",
  CMB: "Colombo",
  DAC: "Dhaka",
  KTM: "Kathmandu",
  HAN: "Hanoi",
  SGN: "Ho Chi Minh City",
  MNL: "Manila",
  BKK: "Bangkok",
  PNH: "Phnom Penh",
  RGN: "Yangon",
  HAN: "Hanoi",
  VTE: "Vientiane",
  LPQ: "Luang Prabang",
  REP: "Siem Reap",
  DAD: "Danang",
  HKT: "Phuket",
  CNX: "Chiang Mai",
  KUL: "Kuala Lumpur",
  PEN: "Penang",
  SIN: "Singapore",
  CGK: "Jakarta",
  LHR: "London Heathrow",
  LGW: "London Gatwick",
  MAN: "Manchester",
  BHX: "Birmingham",
  GLA: "Glasgow",
  EDI: "Edinburgh",
  BRS: "Bristol",
  NCL: "Newcastle",
  LPL: "Liverpool",
  STN: "London Stansted",
  LTN: "London Luton",
  ABZ: "Aberdeen",
  BFS: "Belfast International",
  EMA: "East Midlands",
  LBA: "Leeds Bradford",
  BHD: "Belfast City",
  SOU: "Southampton",
  LCY: "London City",
  CWL: "Cardiff",
  INV: "Inverness",
};

function cityToCode(city) {
  return cityToCodeLookup[city];
}
function codeToCity(code) {
  return codeToCityLookup[code];
}

export { cityToCode, codeToCity };
